si-sce/si_sce2/urls.py
import django
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.defaults import *
from django.contrib import admin
from sistema import views
import os
#from django.views.generic.simple import direct_to_template

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^login/$', views.login_fazer),
    url(r'^si_sce2/static/(?P<path>.*)$', 'django.views.static.serve',{'document_root': os.path.join(os.getcwd(),'static') }),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^base/$', views.base),
    url(r'^login/$', views.login_user),
    url(r'^$', views.home),
    url(r'^logout/$', views.logout_user),
    url(r'^home/$', views.home),

    #Atividade
    url(r'^atividade_cadastrar/$', views.atividade_cadastrar),
    url(r'^atividade_lista/$', views.atividade_lista),
    url(r'^atividade_editar/(?P<id_atividade>[0-9]+)/$', views.atividade_editar),
    url(r'^atividade_excluir/(?P<id_atividade>[0-9]+)/$', views.atividade_excluir),
    url(r'^lista_presenca/(?P<id_atividade>[0-9]+)/$', views.lista_presenca),
    # url(r'^tabela_reservas/$', views.tabela_reservas),
    # url(r'^lista_reserva/(?P<id_atividade>[0-9]+)/$', views.lista_reserva),
    # url(r'^editar_reserva/(?P<id_atividade>[0-9]+)/(?P<id_participante>[0-9]+)/$', views.editar_reserva),
    # url(r'^excluir_reserva/(?P<id_atividade>[0-9]+)/(?P<id_participante>[0-9]+)/$', views.excluir_reserva),
    # url(r'^excluir_reservas/$', views.excluir_reservas),
    # url(r'^excluir_reservas_atividade/(?P<id_atividade>[0-9]+)/$', views.excluir_reservas_atividade),
    url(r'^lista_emails/(?P<id_atividade>[0-9]+)/$', views.lista_emails),
    url(r'^pontodevenda_cadastrar/$', views.pontodevenda_cadastrar),
    url(r'^pontodevenda_excluir/(?P<id_pontodevenda>[0-9]+)/$', views.pontodevenda_excluir),
    url(r'^pontodevenda_lista/$', views.pontodevenda_listar),
    url(r'^pontodevenda_editar/(?P<id_pontodevenda>[0-9]+)/$', views.pontodevenda_editar),
    #url(r'^emails_reserva/(?P<id_atividade>[0-9]+)/$', views.emails_reserva),
    url(r'^participante_dinamica4/(?P<id_local>[0-9]+)/$', views.participante_dinamica4),

    #Participante
    url(r'^participante_cadastrar/$', views.participante_cadastrar),
    url(r'^participante_visualizar/(?P<id_participante>[0-9]+)/$', views.participante_visualizar),
    url(r'^participante_excluir/(?P<id_participante>[0-9]+)/$', views.participante_excluir),
    url(r'^participante_editar/(?P<id_participante>[0-9]+)/$', views.participante_editar),
    url(r'^participante_dinamica/$', views.participante_dinamica),


    #Faculdade
    url(r'^faculdade_cadastrar/$', views.faculdade_cadastrar),
    url(r'^faculdade_visualizar/(?P<id_faculdade>[0-9]+)/$',views.faculdade_visualizar),
    url(r'^faculdade_excluir/(?P<id_faculdade>[0-9]+)/$', views.faculdade_excluir),
    url(r'^faculdade_lista/$', views.faculdade_listar),
    url(r'^faculdade_editar/(?P<id_faculdade>[0-9]+)/$', views.faculdade_editar),
    url(r'^curso_cadastrar/$', views.curso_cadastrar),
    url(r'^curso_visualizar/(?P<id_curso>[0-9]+)/$',views.curso_visualizar),
    url(r'^curso_excluir/(?P<id_curso>[0-9]+)/$', views.curso_excluir),
    url(r'^curso_lista/$', views.curso_listar),
    url(r'^curso_editar/(?P<id_curso>[0-9]+)/$', views.curso_editar),
    url(r'^participante_dinamica2/(?P<id_faculdade>[0-9]+)/$', views.participante_dinamica2),
    url(r'^participante_dinamica3/(?P<id_curso>[0-9]+)/$', views.participante_dinamica3),

    #Vendedor
    url(r'^vendedor_cadastrar/$', views.vendedor_cadastrar),
    url(r'^vendedor_excluir/(?P<id_vendedor>[0-9]+)/$', views.vendedor_excluir),
    url(r'^vendedor_lista/$', views.vendedor_listar),
    url(r'^limpar_pontos/$', views.limpar_pontos),
    url(r'^vendedor_editar/(?P<id_vendedor>[0-9]+)/$', views.vendedor_editar),
    url(r'^vendedor_clientes/(?P<id_vendedor>[0-9]+)/$', views.vendedor_clientes),


    #Compra
    url(r'^lista_compra/(?P<id_participante>[0-9]+)/$', views.lista_compra),

    #Relatorio
    url(r'^tabela_relatorios/$', views.tabela_relatorios),
    url(r'^relatorio_geral/$', views.relatorio_geral),
    url(r'^relatorio_atividade/(?P<id_atividade>[0-9]+)/$', views.relatorio_atividade),
    url(r'^relatorio_atividade2/(?P<id_atividade>[0-9]+)/$', views.relatorio_atividade2),
    url(r'^whatsapp/(?P<id_atividade>[0-9]+)/$', views.whatsapp),
    url(r'^lista_excel/$', views.lista_excel),
    url(r'^lista_ong/$', views.lista_ong),
    url(r'^lista_mailing/$', views.lista_mailing),
    url(r'^lista_brindes/$', views.lista_brindes),
    url(r'^relatorio_vendedores/$', views.relatorio_vendedores),
)

si-sce/sistema/models.py
from django.db import models
import os
import datetime
from django.utils import timezone
from django.contrib.auth.models import User, Group, Permission
from django.dispatch import receiver



tipos_de_compras = (
	('normal', 'Normal'),
	('cortesia', 'Cortesia'),
	('reserva', 'Reserva'),
	('----','----')
)

dia = (
	('Segunda-Feira', "Segunda-Feira"),
	('Terca-Feira', "Terca-Feira"),
	('Quarta-Feira', "Quarta-Feira"),
	('Quinta-Feira', "Quinta-Feira"),
	('Sexta-Feira', "Sexta-Feira"),

)
class Usuario(models.Model):
	nome = models.CharField("Usuario", max_length=64)
	usuario = models.OneToOneField(User, related_name = 'usuario')

	def __unicode__(self):
		return self.nome

class Faculdade(models.Model):
	nome = models.CharField("Faculdade", max_length=64)
	class Meta:
		ordering = ["nome"]
	def __unicode__(self):
		return self.nome

	def participantes(self):
		participantes = Participante.objects.filter(faculdade__nome = self.nome).count()

		return	participantes

class Curso(models.Model):
	nome = models.CharField("Curso", max_length=64)
	class Meta:
		ordering = ["nome"]
	def __unicode__(self):
		return self.nome

	def participantes(self):
		participantes = Participante.objects.filter(curso__nome = self.nome).count()

		return	participantes

class Participante(models.Model):
	nome_completo = models.CharField("Nome completo", max_length=256)
	cpf = models.CharField("CPF", max_length=16)
	faculdade = models.ForeignKey(Faculdade)
	curso = models.ForeignKey(Curso)
	ano_ingresso = models.IntegerField("Ano de ingresso")
	e_mail = models.EmailField("E-mail")
	telefone = models.CharField("Telefone", max_length=16)
	moleskine = models.NullBooleanField()
	lancheira = models.NullBooleanField()
	aceita_divulgacao = models.NullBooleanField()
	ong = models.NullBooleanField()
	def __unicode__(self):
		return self.nome_completo

	def atividades(self):
		compradas = Compra.objects.filter(participante__nome_completo = self.nome_completo, comprado=True).count()
		cortesia = Compra.objects.filter(participante__nome_completo = self.nome_completo, cortesia=True).count()


		return	compradas + cortesia
	def presencas(self):
		presencas = Compra.objects.filter(participante__nome_completo = self.nome_completo, presente=True).count()
		return presencas


class Atividade(models.Model):
	nome = models.CharField("Nome", max_length=64)
	dia = models.CharField("Dia", choices = dia, max_length = 64)
	horario = models.CharField("Horario", max_length=64)
	# descricao = models.CharField("Descricao",max_length=64)
	cap_participantes = models.IntegerField("Capacidade de Participantes")
	overbooking = models.IntegerField("Overbooking", null=True, blank = True)
	cap_atual = models.IntegerField("Capacidade Atual")
	pont_vendas = models.IntegerField("Pontuacao de Vendas")
	preco = models.IntegerField("Preco")

	def __unicode__(self):
		return self.nome

	def cap_atual(self):
		compradas = Compra.objects.filter(atividade__nome=self.nome, comprado=True).count()
		# reservadas = Compra.objects.filter(atividade__nome=self.nome, reservado=True).count()
		cortesias = Compra.objects.filter(atividade__nome=self.nome, cortesia=True).count()
		cap_inicial = self.cap_participantes
		overbooking = self.overbooking
		cap_atual = cap_inicial + overbooking - cortesias - compradas

		return	cap_atual

	# def reservas(self):
	# 	reservas = Compra.objects.filter(atividade__nome=self.nome, reservado=True).count()

	# 	return reservas

	def vendas(self):
		vendidos = Compra.objects.filter(atividade__nome=self.nome, comprado=True).count()
		cortesia = Compra.objects.filter(atividade__nome=self.nome, cortesia=True).count()
		vendas = vendidos + cortesia
		return vendas

class Email(models.Model):
	corpo = models.CharField("Corpo", max_length=512)
	assunto = models.CharField("Assunto", max_length=64)

	def __unicode__(self):
		return self.nome

class Vendedor(models.Model):
	nome = models.CharField("Nome", max_length=64)
	pontos = models.IntegerField("Pontos", null=True, blank=True)
	class Meta:
		ordering = ["nome"]
	def __unicode__(self):
		return self.nome


class PontodeVenda(models.Model):
	nome = models.CharField("Local de Venda", max_length=64)
	class Meta:
		ordering = ["nome"]
	def __unicode__(self):
		return self.nome

class Compra(models.Model):
	participante = models.ForeignKey(Participante)
	atividade = models.ForeignKey(Atividade)
	local = models.ForeignKey(PontodeVenda, null=True, blank = True)
	vendedor = models.ForeignKey(Vendedor, null=True, blank = True)
	preco_pagar = models.IntegerField("Preco", null=True, blank=True)
	presente = models.BooleanField(default = False)
	comprado = models.BooleanField(default = False)
	#reservado = models.BooleanField(default = False)
	cortesia = models.BooleanField(default = False)
	pontos = models.IntegerField("Pontos", null=True, blank=True)

si-sce/sistema/forms.py
# Embedded file name: C:\Users\Gabriel\Documents\si_sce2\sistema\forms.py
import os, sys
from sistema.models import *
from django import forms
from django.contrib.localflavor.br.forms import *
from django.contrib.auth.forms import PasswordChangeForm
from django.forms import ModelForm, TextInput, Select
from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory

# class LogarPontodeVendaForm(forms.ModelForm):

#     class Meta:
#         model = Usuario
#         fields = ['local']

class CriarParticipanteForm(forms.ModelForm):

    class Meta:
        model = Participante


class CriarAtividadeForm(forms.ModelForm):

    class Meta:
        model = Atividade


class CriarFaculdadeForm(forms.ModelForm):

    class Meta:
        model = Faculdade

class CriarCursoForm(forms.ModelForm):

    class Meta:
        model = Curso

class CriarPontodeVendaForm(forms.ModelForm):

    class Meta:
        model = PontodeVenda

class CriarVendedorForm(forms.ModelForm):

    class Meta:
        model = Vendedor
        fields = ['nome']


class LoginForm(forms.Form):
    usuario = forms.CharField(label='Usuario', widget=forms.TextInput(attrs={'class': 'text'}))
    senha = forms.CharField(label='Senha', widget=forms.PasswordInput(attrs={'class': 'text'}))


class ListaPresencaForm(forms.ModelForm):

    class Meta:
        model = Compra
        fields = ['presente']


class CompraForm(forms.ModelForm):

    class Meta:
        model = Compra
        fields = ['comprado',
         'cortesia',
         'local',
         'vendedor']



class EmailForm(forms.ModelForm):

    class Meta:
        model = Email
        fields = ['assunto', 'corpo']

si-sce/sistema/templates/alerta.html
<<html>
<head>
	<title></title>
</head>
<body>
	<script>alert('{{alerta}}');javascript:history.back();</script>
</body>
</html>

si-sce/sistema/templates/atividade_cadastrar.html
{% extends "base.html" %}
{% load i18n %}
{%block conteudo%}

<div class="scrollable wrapper">
<!--row start-->


            <div class="box-info">
            <h3><b>Cadastro de atividade</b></h3>
                      <hr>
              <div class="widget-body">
                    <p>
                    <form method= "POST" action ="/atividade_cadastrar/" data-ajax="false" class="form-horizontal" enctype="multipart/form-data"> {% csrf_token %}
                      <br>

                      <table style="display: table; border-spacing:7px; border-collapse: separate;">
                      {%for field in criar_atividade%}
                        <tr>
                          <td>{{field.label}}</td>
                          <td>{{field}}</td>
                        </tr>
                      {%endfor%}
                      </table><br>
                    <div style ="margin-left:8em">
                    <button input type="submit" class="btn btn-warning" style="margin-top: 8px; width: 150px; border-radius: 1em;">Cadastrar</button>
                    </div>


                    </form>
                    </p>

      </div>
</div>
{%endblock conteudo%}
</html>

si-sce/sistema/templates/atividade_lista.html
{% extends "base.html" %}
{% load i18n %}

{%block conteudo%}



<div class="scrollable wrapper">

        <div class="box-info">
             <h3><b>Atividades cadastradas</b></h3>
            <hr>
            <div class="widget-content no-padding" style="overflow-x: auto;">
                <div class="widget-content-inner">
                    <table class="display table table-bordered table-striped table-hover dataTable" id="tabela-atividades" >
                        <thead>

                            <tr style >
                                <th>Atividade</th>
                                <th>Dia</th>
                                <th>Horario</th>
                                <th>Vagas</th>

                                <!-- <th>Reservas</th> -->
                                <th>Valor</th>
                                <th>Vendas</th>
                                <th>Pontos</th>
                                <th>Overbooking</th>
                                <th></th>
                                {%if adm%}
                                <th></th>
                                <th></th>
                                {%endif%}
                            </tr>
                        </thead>
                        <tbody>
                            {% for atividade in atividade_lista %}
                            <tr class="odd gradeA">
                                <td>{{atividade.nome}}</td>
                                <td>{{atividade.dia}}</td>
                                <td>{{atividade.horario}}</td>
                                <td>{{atividade.cap_atual}}</td>

                   <!--              <td>{{atividade.reservas}}</td> -->
                                <td>R$ {{atividade.preco}},00</td>
                                <td>{{atividade.vendas}}</td>
                                <td>{{atividade.pont_vendas}}</td>
                                <td>{{atividade.overbooking}}</td>
                                <td><a href="/lista_presenca/{{atividade.id}}"><button type="button" class="btn btn-warning" style="border-radius:1em">Lista de presença</button></a></td>
                                {%if adm%}
                                <td><a href="/atividade_editar/{{atividade.id}}"><button type="button" class="btn btn-warning" style="border-radius:1em">Editar</button></a></td>
                                <td><a href="/atividade_excluir/{{atividade.id}}" OnClick= "return confirm('Tem certeza que quer excluir este cadastro? Esta ação não poderá ser desfeita.')"><button type="button" class="btn btn-warning" style="border-radius:1em">Excluir</button></a></td>
                                {%endif%}
                                <!--<td><a href="/aluno_visualizar/{{item.id}}"> Ver Descricao </a></td>
                                <td><a href="/aluno_deletar/{{item.id}} " OnClick= "return confirm('Tem certeza que quer excluir este cadastro? Esta ação não poderá ser desfeita.')">Excluir</a></td> -->
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

    </div>
</div>

{%endblock conteudo%}
</html>

si-sce/sistema/templates/email_enviar.html
{% extends "base.html" %}
{% load i18n %}
{%block conteudo%}

<div class="scrollable wrapper">
<!--row start-->


            <div class="box-info">
            <h3><b>Enviar e-mail</b></h3>
                      <hr>
              <div class="widget-body">
                    <p>
                    <form method= "POST" action ="" data-ajax="false" class="form-horizontal" enctype="multipart/form-data"> {% csrf_token %}
                      <br>

                      <table>
                      {%for field in email_enviar%}
                        <tr>
                          <td>{{field.label}}</td>
                          <td>{{field}}</td>
                        </tr>
                      {%endfor%}
                      </table>

                    <button input type="submit" class="btn btn-warning" style="margin-top: 8px; width: 150px;">Enviar</button>


                    </form>
                    </p>

      </div>
</div>
{%endblock conteudo%}
</html>

si-sce/sistema/templates/lista_presenca2.html
{% extends "base.html" %}
{% load i18n %}

{%block conteudo%}
<style>

input[type="checkbox"] {
    height: 20px;
    width:20px;
}
</style>
<div class="scrollable wrapper">
        <div class="box-info">
             <h3><b>Lista de presença </b>- <i>{{atividade_selecionada.nome.capitalize}}</i> {%if adm%}<br><br><a href="/lista_emails/{{atividade_selecionada.id}}/"><button type="button" class="btn btn-warning" style="border-radius:1em">Enviar e-mail de confirmação</button></a> <a href="/relatorio_atividade2/{{id_atividade}}"><button type="button" class="btn btn-warning" style="border-radius:1em"> Imprimir lista de presença</button></a>{%endif%} <br></h3>
             <hr>

            <div class="widget-content no-padding" style="overflow-x: auto;">
                <div class="widget-content-inner">
                <form method= "POST" action ="/lista_presenca/{{atividade_selecionada.id}}/" data-ajax="false" class="form-horizontal" enctype="multipart/form-data"> {% csrf_token %}
                    <table class="display table table-bordered table-striped table-hover dataTable" id="tabela-presenca" >
                        <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Telefone</th>
                                    <th>E-mail</th>
                                    <th>Faculdade</th>
                                    <th>Curso</th>
                                    <th>Presença</th>

                                    <th>Presença2</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lista in lista_form %}
                                <tr class="">
                                    <td>{{lista.0.nome_completo}}</td>
                                    <td>{{lista.0.telefone}}</td>
                                    <td>{{lista.0.e_mail}}</td>
                                    <td>{{lista.0.faculdade}}</td>
                                    <td>{{lista.0.curso}}</td>
                                    <td><a href="/participante_presente/{{atividade.id}}/{{lista.0.id}}" OnClick= "return confirm('Tem certeza que quer excluir este cadastro? Esta ação não poderá ser desfeita.')"><button type="button" class="btn btn-warning" style="border-radius:1em">Excluir</button></a></td>


                                    <td>{{lista.1.presente}}</td>

                                    <!--<td><a href="/aluno_visualizar/{{item.id}}"> Ver Descricao </a></td>
                                <td><a href="/aluno_deletar/{{item.id}} " OnClick= "return confirm('Tem certeza que quer excluir este cadastro? Esta ação não poderá ser desfeita.')">Excluir</a></td> -->
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table><br>
                </div>
            </div>

        </div>
                        <div align="center">
                        <button type="submit" class="btn btn-warning" style="border-radius:1em; align:center"  OnClick= "return confirm('Limpou o campo de busca antes de salvar?')">Salvar</button>
                        </div>
                        </form>




        </div>
        <div class="scrollable wrapper">

        <div class="box-info">
        <h3><b>Compareceram à atividade</b> {# <i>{{atividade_selecionada.nome.capitalize}}</i>  #}{{porcentagem_presenca}}% do esperado</h3>
             <hr>
            <div class="widget-content no-padding">
                <div class="widget-content-inner">
                    <table class="display table table-bordered table-striped table-hover dataTable" id="tabela-presenca2" >
                        <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>Telefone</th>
                                    <th>E-mail</th>
                                    <th>Faculdade</th>
                                    <th>Curso</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lista in lista_presentes %}
                                <tr class="odd gradeA">
                                    <td>{{lista.0.nome_completo}}</td>
                                    <td>{{lista.0.telefone}}</td>
                                    <td>{{lista.0.e_mail}}</td>
                                    <td>{{lista.0.faculdade}}</td>
                                    <td>{{lista.0.curso}}</td>
                                    <!--<td><a href="/aluno_visualizar/{{item.id}}"> Ver Descricao </a></td>
                                <td><a href="/aluno_deletar/{{item.id}} " OnClick= "return confirm('Tem certeza que quer excluir este cadastro? Esta ação não poderá ser desfeita.')">Excluir</a></td> -->
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

        </div>
    </div>
    {%if adm%}
    <div align="center">
    <td><a href="/relatorio_atividade/{{id_atividade}}"><button type="button" class="btn btn-warning" style="border-radius:1em">Gerar excel</button></a></td>
    </div><br><br>
    {%endif%}
    </div>
{%endblock conteudo%}
</html>

si-sce/sistema/templates/participante_cadastrar.html
{% extends "base.html" %}
{% load i18n %}
{%block conteudo%}

<div class="scrollable wrapper">
<!--row start-->


<div class="box-info">
    <h3><b>Cadastro de participante</b></h3>
    <hr>
    <div class="widget-body">
        <p>
            <form method= "POST" action ="/participante_cadastrar/" data-ajax="false" class="form-horizontal row-border" enctype="multipart/form-data"> {% csrf_token %}
                <br>


                    {%for field in participante_form%}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">{{field.label}}</label>
                            <div class="col-sm-3" style="width:250px;">{{field}}</div>
                        </div>

                    {%endfor%}
                <br>
                <div style ="margin-left:7em">
                    <button input type="submit" class="btn btn-warning" id= "test" style="margin-top: 8px; width: 150px; border-radius: 1em;">Cadastrar</button>
                </div>
            </form>
        </p>
    </div>
</div>
<script src="//code.jquery.com/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.maskedinput.min.js"></script>

<script type="text/javascript">
$("#id_telefone").mask("(99) 99999-9999",{placeholder:"(  )      -    "});
$("#id_ano_ingresso").mask("9999",{placeholder:""});
$("#id_cpf").mask("999.999.999-99",{placeholder:"   .   .   -  "});

$("#test").click(function() {
    var all = true;
    var x = 0;
    var y = $(':input:text').length;
    $(':input:text').each(function() {
        if (this.value == "") {
          x = x + 1;
          all = false;
        }
    });
    if (all) return true;
    alert("Existem campos vazios!");
    return false;
});

</script>
{%endblock conteudo%}
</html>

si-sce/sistema/templates/participante_editar.html
{% extends "base.html" %}
{% load i18n %}

{%block conteudo%}
<div class="scrollable wrapper">
    <div class="box-info">



        <form method= "POST" action ="/participante_editar/{{participante.id}}/" data-ajax="false" class="form-horizontal"  enctype="multipart/form-data">
        {% csrf_token %}
        <h3><b>Editar informações pessoais</b></h3> <hr>
        <table style="display: table; border-spacing:7px; border-collapse: separate;">
        {%for field in participante_editar%}
          <tr>
            <td>{{field.label}}</td>
            <td>{{ field }}</td>
          </tr>
        {%endfor%}
        </table><br>
        <a href="/participante_visualizar/{{participante.id}}"><button type="button" class="btn btn-warning" style="border-radius:1em">Voltar</button></a>
        <button input type="submit" id = "test" class="btn btn-warning" style="border-radius:1em">Salvar</button>

        </form>
    </div>
</div>
<script src="//code.jquery.com/jquery-2.0.3.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.maskedinput.min.js"></script>
<script type="text/javascript">
$("#id_telefone").mask("(99)99999-9999",{placeholder:""});
$("#id_ano_ingresso").mask("9999",{placeholder:""});
$("#test").click(function() {
    var all = true;
    var x = 0;
    var y = $(':input:text').length;
    $(':input:text').each(function() {
        if (this.value == "") {
          x = x + 1;
          all = false;
        }
    });
    if (all) return true;
    alert("Existem campos vazios!");
    return false;
});

</script>
{%endblock conteudo%}
</html>

si-sce/sistema/templates/pontodevenda_cadastrar.html
{% extends "base.html" %}
{% load i18n %}
{%block conteudo%}

<div class="scrollable wrapper">
<!--row start-->


            <div class="box-info">
            <h3><b>Cadastro de ponto de venda</b></h3>
            <hr>
      <div class="widget-body">
            <p>
            <form method= "POST" action ="/pontodevenda_cadastrar/" data-ajax="false" class="form-horizontal" enctype="multipart/form-data"> {% csrf_token %}
              <br>

              <table>
              {%for field in pontodevenda_form%}
                <tr>
                  <td>{{field.label}}</td>
                  <td>{{field}}</td>
                </tr>
              {%endfor%}
              </table>
              <br>

            <div style ="margin-left:6em">
            <button input type="submit" class="btn btn-warning" style="margin-top: 8px; width: 150px; border-radius: 1em;">Cadastrar</button>
            </div>
            </form>
            </p>
      </div>
{%endblock conteudo%}
</html>